name: Snyk and ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push x86_64 image
        id: build_x86
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/M4ximito/Zadanie2:${{ github.run_number }}-x86_64

      - name: Test image for CVEs
        run: trivy image ghcr.io/M4ximito/Zadanie2:${{ github.run_number }}-x86_64

      - name: Build and push arm64 image
        id: build_arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/M4ximito/Zadanie2:${{ github.run_number }}-arm64
          builder: multi-platform

      - name: Get SemVer version
        id: semver
        run: echo "::set-output name=version::$(date +'%Y.%-m.%-d')-$(echo ${{ github.run_number }} | cut -c1-7)"
