name: Snyk and ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Login to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Scan Docker image with Snyk
      run: npx snyk test --all-projects --docker ghcr.io/M4ximito/zadanie2:latest-x86_64 --json > snyk-results.json

    - name: Publish Snyk results as artifact
      uses: actions/upload-artifact@v2
      with:
        name: snyk-results
        path: snyk-results.json
