name: Build and Publish Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push x86_64 image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.dev
        platforms: linux/amd64
        push: true
        tags: ghcr.io/M4ximito/zadanie2:latest-x86_64

    - name: Login to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Scan Docker image with Snyk
      run: npx snyk test --all-projects --docker ghcr.io/M4ximito/zadanie2:latest-x86_64 --json > snyk-results.json

    - name: Publish Snyk results as artifact
      uses: actions/upload-artifact@v2
      with:
        name: snyk-results
        path: snyk-results.json
